{% set name = "qnorm" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c77432b0529989ca81685b537a61158e9a23f9599965edd2a9cc2bd2eb4e0ad6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - toml
    - pip
  run:
    - python >=3.6
    - numba
    - numpy
    - pandas

test:
  imports:
    - qnorm

about:
  home: https://github.com/Maarten-vd-Sande/qnorm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy and fast quantile normalization in Python

extra:
  recipe-maintainers:
    - Maarten-vd-Sande
