{% set name = "qnorm" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62bdd09cbbf18f2bac40fdb2f218b19213824a30253f2a3b988e00a84eca72bc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - toml
    - pip
  run:
    - python >=3.6
    - numba
    - numpy

test:
  imports:
    - qnorm

about:
  home: https://github.com/Maarten-vd-Sande/qnorm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy and fast quantile normalization in Python

extra:
  recipe-maintainers:
    - Maarten-vd-Sande
