{% set name = "qnorm" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1e67cc0478db1167d4c614f47274ad6637561d0b2a84ada12ab7f1744edc48c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - toml
    - pip
  run:
    - python >=3.6
    - numba
    - numpy

test:
  imports:
    - qnorm

about:
  home: https://github.com/Maarten-vd-Sande/qnorm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy and fast quantile normalization in Python

extra:
  recipe-maintainers:
    - Maarten-vd-Sande
